
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.athenamod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.sounds.SoundEvent;
import net.minecraft.resources.ResourceLocation;

import net.mcreator.athenamod.AthenaModMod;

public class AthenaModModSounds {
	public static final DeferredRegister<SoundEvent> REGISTRY = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, AthenaModMod.MODID);
	public static final RegistryObject<SoundEvent> CRICKETCHIRP = REGISTRY.register("cricketchirp", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "cricketchirp")));
	public static final RegistryObject<SoundEvent> APOLLOHISS = REGISTRY.register("apollohiss", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "apollohiss")));
	public static final RegistryObject<SoundEvent> ALIEN = REGISTRY.register("alien", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "alien")));
	public static final RegistryObject<SoundEvent> ALIENHURT = REGISTRY.register("alienhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "alienhurt")));
	public static final RegistryObject<SoundEvent> ALIENDEATH = REGISTRY.register("aliendeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "aliendeath")));
	public static final RegistryObject<SoundEvent> LASER = REGISTRY.register("laser", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "laser")));
	public static final RegistryObject<SoundEvent> AUTOGUNSHOT = REGISTRY.register("autogunshot", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "autogunshot")));
	public static final RegistryObject<SoundEvent> GUNSHOT = REGISTRY.register("gunshot", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "gunshot")));
	public static final RegistryObject<SoundEvent> HOVER = REGISTRY.register("hover", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "hover")));
	public static final RegistryObject<SoundEvent> ROCKET = REGISTRY.register("rocket", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "rocket")));
	public static final RegistryObject<SoundEvent> ZILLAROAR1 = REGISTRY.register("zillaroar1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "zillaroar1")));
	public static final RegistryObject<SoundEvent> ZILLAROAR2 = REGISTRY.register("zillaroar2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "zillaroar2")));
	public static final RegistryObject<SoundEvent> EXPLOSION = REGISTRY.register("explosion", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "explosion")));
	public static final RegistryObject<SoundEvent> BEEFCAKE = REGISTRY.register("beefcake", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "beefcake")));
	public static final RegistryObject<SoundEvent> NERDALIVE = REGISTRY.register("nerdalive", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "nerdalive")));
	public static final RegistryObject<SoundEvent> NERDHURT = REGISTRY.register("nerdhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "nerdhurt")));
	public static final RegistryObject<SoundEvent> NERDDEATH = REGISTRY.register("nerddeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "nerddeath")));
	public static final RegistryObject<SoundEvent> RAPTORAMBIENT = REGISTRY.register("raptorambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "raptorambient")));
	public static final RegistryObject<SoundEvent> RAPTORHURT = REGISTRY.register("raptorhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "raptorhurt")));
	public static final RegistryObject<SoundEvent> RAPTORDEATH = REGISTRY.register("raptordeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "raptordeath")));
	public static final RegistryObject<SoundEvent> TREXAMB = REGISTRY.register("trexamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "trexamb")));
	public static final RegistryObject<SoundEvent> TREXHURT = REGISTRY.register("trexhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "trexhurt")));
	public static final RegistryObject<SoundEvent> TREXDEATH = REGISTRY.register("trexdeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "trexdeath")));
	public static final RegistryObject<SoundEvent> AKBAR = REGISTRY.register("akbar", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "akbar")));
	public static final RegistryObject<SoundEvent> SOLDIERAMB = REGISTRY.register("soldieramb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "soldieramb")));
	public static final RegistryObject<SoundEvent> SOLDIERHURT = REGISTRY.register("soldierhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "soldierhurt")));
	public static final RegistryObject<SoundEvent> SOLDIERDEATH = REGISTRY.register("soldierdeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "soldierdeath")));
	public static final RegistryObject<SoundEvent> TERRORAMB = REGISTRY.register("terroramb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "terroramb")));
	public static final RegistryObject<SoundEvent> TERRORHURT = REGISTRY.register("terrorhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "terrorhurt")));
	public static final RegistryObject<SoundEvent> LUMBERAMB = REGISTRY.register("lumberamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "lumberamb")));
	public static final RegistryObject<SoundEvent> LUMBERHURT = REGISTRY.register("lumberhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "lumberhurt")));
	public static final RegistryObject<SoundEvent> LUMBERDEATH = REGISTRY.register("lumberdeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "lumberdeath")));
	public static final RegistryObject<SoundEvent> THOTAMB = REGISTRY.register("thotamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "thotamb")));
	public static final RegistryObject<SoundEvent> THOTHURT = REGISTRY.register("thothurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "thothurt")));
	public static final RegistryObject<SoundEvent> THOTDEATH = REGISTRY.register("thotdeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "thotdeath")));
	public static final RegistryObject<SoundEvent> CIV1AMB = REGISTRY.register("civ1amb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "civ1amb")));
	public static final RegistryObject<SoundEvent> CIV1HURT = REGISTRY.register("civ1hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "civ1hurt")));
	public static final RegistryObject<SoundEvent> CIV1DEATH = REGISTRY.register("civ1death", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "civ1death")));
	public static final RegistryObject<SoundEvent> CKAMB = REGISTRY.register("ckamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "ckamb")));
	public static final RegistryObject<SoundEvent> CKHURT = REGISTRY.register("ckhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "ckhurt")));
	public static final RegistryObject<SoundEvent> CKDEATH = REGISTRY.register("ckdeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "ckdeath")));
	public static final RegistryObject<SoundEvent> DONTLIKE = REGISTRY.register("dontlike", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "dontlike")));
	public static final RegistryObject<SoundEvent> TAYKAMB = REGISTRY.register("taykamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "taykamb")));
	public static final RegistryObject<SoundEvent> HARD = REGISTRY.register("hard", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "hard")));
	public static final RegistryObject<SoundEvent> HARD2 = REGISTRY.register("hard2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "hard2")));
	public static final RegistryObject<SoundEvent> IMPAMB = REGISTRY.register("impamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "impamb")));
	public static final RegistryObject<SoundEvent> IMPHURT = REGISTRY.register("imphurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "imphurt")));
	public static final RegistryObject<SoundEvent> IMPDEATH = REGISTRY.register("impdeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "impdeath")));
	public static final RegistryObject<SoundEvent> DEMONAMB = REGISTRY.register("demonamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "demonamb")));
	public static final RegistryObject<SoundEvent> DEMONHURT = REGISTRY.register("demonhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "demonhurt")));
	public static final RegistryObject<SoundEvent> DEMONDEATH = REGISTRY.register("demondeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "demondeath")));
	public static final RegistryObject<SoundEvent> TAYKFREED = REGISTRY.register("taykfreed", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "taykfreed")));
	public static final RegistryObject<SoundEvent> TAYKLOUDER = REGISTRY.register("tayklouder", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "tayklouder")));
	public static final RegistryObject<SoundEvent> ROCKMONSTEREMERGE = REGISTRY.register("rockmonsteremerge", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "rockmonsteremerge")));
	public static final RegistryObject<SoundEvent> ROCKMONSTERHURT = REGISTRY.register("rockmonsterhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "rockmonsterhurt")));
	public static final RegistryObject<SoundEvent> ROCKMONSTERDEATH = REGISTRY.register("rockmonsterdeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "rockmonsterdeath")));
	public static final RegistryObject<SoundEvent> SATANHEAL = REGISTRY.register("satanheal", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "satanheal")));
	public static final RegistryObject<SoundEvent> SATANHURT = REGISTRY.register("satanhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "satanhurt")));
	public static final RegistryObject<SoundEvent> SATANDEATH = REGISTRY.register("satandeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "satandeath")));
	public static final RegistryObject<SoundEvent> SATANAMB = REGISTRY.register("satanamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "satanamb")));
	public static final RegistryObject<SoundEvent> SATANSUMMON = REGISTRY.register("satansummon", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "satansummon")));
	public static final RegistryObject<SoundEvent> SATANSPAWN = REGISTRY.register("satanspawn", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "satanspawn")));
	public static final RegistryObject<SoundEvent> SHOTGUN = REGISTRY.register("shotgun", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "shotgun")));
	public static final RegistryObject<SoundEvent> SHOTGUNBLAST = REGISTRY.register("shotgunblast", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "shotgunblast")));
	public static final RegistryObject<SoundEvent> RIFLE = REGISTRY.register("rifle", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "rifle")));
	public static final RegistryObject<SoundEvent> SMG = REGISTRY.register("smg", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "smg")));
	public static final RegistryObject<SoundEvent> REVOLVER = REGISTRY.register("revolver", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "revolver")));
	public static final RegistryObject<SoundEvent> SNIPER = REGISTRY.register("sniper", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "sniper")));
	public static final RegistryObject<SoundEvent> WIZARDAMB = REGISTRY.register("wizardamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "wizardamb")));
	public static final RegistryObject<SoundEvent> WIZARDHURT = REGISTRY.register("wizardhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "wizardhurt")));
	public static final RegistryObject<SoundEvent> WIZARDDEATH = REGISTRY.register("wizarddeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "wizarddeath")));
	public static final RegistryObject<SoundEvent> CIV2AMB = REGISTRY.register("civ2amb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "civ2amb")));
	public static final RegistryObject<SoundEvent> CIV2HURT = REGISTRY.register("civ2hurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "civ2hurt")));
	public static final RegistryObject<SoundEvent> CIV2DEATH = REGISTRY.register("civ2death", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "civ2death")));
	public static final RegistryObject<SoundEvent> FORTNITEDIE = REGISTRY.register("fortnitedie", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "fortnitedie")));
	public static final RegistryObject<SoundEvent> DOOMSDAY = REGISTRY.register("doomsday", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "doomsday")));
	public static final RegistryObject<SoundEvent> DOOMAMB = REGISTRY.register("doomamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "doomamb")));
	public static final RegistryObject<SoundEvent> DOOMHURT = REGISTRY.register("doomhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "doomhurt")));
	public static final RegistryObject<SoundEvent> DOOMDEATH = REGISTRY.register("doomdeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "doomdeath")));
	public static final RegistryObject<SoundEvent> KNIGHTAMB = REGISTRY.register("knightamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "knightamb")));
	public static final RegistryObject<SoundEvent> KNIGHTHURT = REGISTRY.register("knighthurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "knighthurt")));
	public static final RegistryObject<SoundEvent> KNIGHTDEATH = REGISTRY.register("knightdeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "knightdeath")));
	public static final RegistryObject<SoundEvent> TYLERAMB = REGISTRY.register("tyleramb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "tyleramb")));
	public static final RegistryObject<SoundEvent> TYLERHURT = REGISTRY.register("tylerhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "tylerhurt")));
	public static final RegistryObject<SoundEvent> TYLERDEATH = REGISTRY.register("tylerdeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "tylerdeath")));
	public static final RegistryObject<SoundEvent> TREEHOME95 = REGISTRY.register("treehome95", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "treehome95")));
	public static final RegistryObject<SoundEvent> KANYEAMB = REGISTRY.register("kanyeamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "kanyeamb")));
	public static final RegistryObject<SoundEvent> KANYEHURT = REGISTRY.register("kanyehurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "kanyehurt")));
	public static final RegistryObject<SoundEvent> KANYEDIE = REGISTRY.register("kanyedie", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "kanyedie")));
	public static final RegistryObject<SoundEvent> CHRISCHANAMB = REGISTRY.register("chrischanamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "chrischanamb")));
	public static final RegistryObject<SoundEvent> CHRISCHANHURT = REGISTRY.register("chrischanhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "chrischanhurt")));
	public static final RegistryObject<SoundEvent> CHRISCHANDEATH = REGISTRY.register("chrischandeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "chrischandeath")));
	public static final RegistryObject<SoundEvent> OBAMAAMB = REGISTRY.register("obamaamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "obamaamb")));
	public static final RegistryObject<SoundEvent> OBAMAHURT = REGISTRY.register("obamahurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "obamahurt")));
	public static final RegistryObject<SoundEvent> OBAMADEATH = REGISTRY.register("obamadeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "obamadeath")));
	public static final RegistryObject<SoundEvent> BIBLEUSED = REGISTRY.register("bibleused", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "bibleused")));
	public static final RegistryObject<SoundEvent> ROBOTAMBIENT = REGISTRY.register("robotambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "robotambient")));
	public static final RegistryObject<SoundEvent> ROBOTWALK = REGISTRY.register("robotwalk", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "robotwalk")));
	public static final RegistryObject<SoundEvent> ROBOTHURT = REGISTRY.register("robothurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "robothurt")));
	public static final RegistryObject<SoundEvent> ROBOTDEATH = REGISTRY.register("robotdeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "robotdeath")));
	public static final RegistryObject<SoundEvent> DOORUNLOCK = REGISTRY.register("doorunlock", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "doorunlock")));
	public static final RegistryObject<SoundEvent> TRUMPAMB = REGISTRY.register("trumpamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "trumpamb")));
	public static final RegistryObject<SoundEvent> TRUMPHURT = REGISTRY.register("trumphurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "trumphurt")));
	public static final RegistryObject<SoundEvent> TRUMPDEATH = REGISTRY.register("trumpdeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "trumpdeath")));
	public static final RegistryObject<SoundEvent> ROBOTHURT2 = REGISTRY.register("robothurt2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "robothurt2")));
	public static final RegistryObject<SoundEvent> ROBOTAMB2 = REGISTRY.register("robotamb2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "robotamb2")));
	public static final RegistryObject<SoundEvent> ROBOTDEATH2 = REGISTRY.register("robotdeath2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "robotdeath2")));
	public static final RegistryObject<SoundEvent> DAISYAMB = REGISTRY.register("daisyamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "daisyamb")));
	public static final RegistryObject<SoundEvent> DAISYHURT = REGISTRY.register("daisyhurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "daisyhurt")));
	public static final RegistryObject<SoundEvent> DAISYDEATH = REGISTRY.register("daisydeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "daisydeath")));
	public static final RegistryObject<SoundEvent> HEAVENTHEME = REGISTRY.register("heaventheme", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "heaventheme")));
	public static final RegistryObject<SoundEvent> BRONTOAMB = REGISTRY.register("brontoamb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "brontoamb")));
	public static final RegistryObject<SoundEvent> BRONTOHURT = REGISTRY.register("brontohurt", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "brontohurt")));
	public static final RegistryObject<SoundEvent> BRONTODEATH = REGISTRY.register("brontodeath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "brontodeath")));
	public static final RegistryObject<SoundEvent> DINOWALK = REGISTRY.register("dinowalk", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "dinowalk")));
	public static final RegistryObject<SoundEvent> DAISYAMB2 = REGISTRY.register("daisyamb2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "daisyamb2")));
	public static final RegistryObject<SoundEvent> DAISYEND = REGISTRY.register("daisyend", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "daisyend")));
	public static final RegistryObject<SoundEvent> DAISYHURT2 = REGISTRY.register("daisyhurt2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "daisyhurt2")));
	public static final RegistryObject<SoundEvent> NUKE = REGISTRY.register("nuke", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "nuke")));
	public static final RegistryObject<SoundEvent> NUKESIREN = REGISTRY.register("nukesiren", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("athena_mod", "nukesiren")));
}
